Repository Algebraic-Programming/ALP, pull requests merged in 2023-06, with the labels that each got.

#200 642 separating built from tested backends
  .gitlab-ci.yml
  CMakeLists.txt
  cmake/AddGRBTests.cmake
  docs/Build_and_test_infra.md
  tests/CMakeLists.txt
  tests/unit/CMakeLists.txt
  tests/unit/buildMatrixUnique.cpp
  tests/unit/unittests.sh
Labels: bug

#180 623 Collecting test coverage information from tests
  .gitlab-ci.yml
  CMakeLists.txt
  NOTICE
  README.md
  bootstrap.sh
  cmake/CompileFlags.cmake
  cmake/Coverage.cmake
  cmake/FindGCov.cmake
  cmake/FindGcovr.cmake
  cmake/Utils.cmake
  cmake/simple.cpp
  docs/Build_and_test_infra.md
  src/graphblas/CMakeLists.txt
  tests/parse_env.sh
  tests/unit/CMakeLists.txt
  tests/unit/unittests.sh
Labels: documentation, enhancement

#202 Fix GitLab CI + small improvements
  .gitlab-ci.yml
  cmake/CompileFlags.cmake
  docs/Build_and_test_infra.md
  src/transition/CMakeLists.txt
Labels: bug

#184 632 Matrix eWiseApply implemented but not declared in base
  include/graphblas/base/blas3.hpp
  include/graphblas/base/io.hpp
  include/graphblas/bsp1d/blas2.hpp
  include/graphblas/bsp1d/blas3.hpp
  include/graphblas/hyperdags/blas2.hpp
  include/graphblas/hyperdags/blas3.hpp
  include/graphblas/hyperdags/io.hpp
  include/graphblas/nonblocking/blas3.hpp
  include/graphblas/nonblocking/io.hpp
  include/graphblas/reference/blas3.hpp
  include/graphblas/reference/io.hpp
Labels: enhancement

#183 629 missing type definitions for multiple backends
  include/graphblas/bsp1d/matrix.hpp
  include/graphblas/hyperdags/matrix.hpp
  include/graphblas/nonblocking/matrix.hpp
  tests/unit/CMakeLists.txt
  tests/unit/static_asserts/matrix.cpp
Labels: enhancement

#192 634 Add support for matrixmarket integer type
  include/graphblas/utils/parser/MatrixFileReaderBase.hpp
Labels: enhancement
