Repository Algebraic-Programming/ALP, pull requests merged in 2024-02, with the labels that each got.

#291 289 failed call of ewiselambda
  include/graphblas/reference/blas2.hpp
  tests/unit/CMakeLists.txt
  tests/unit/eWiseLambda.cpp
  tests/unit/unittests.sh
Labels: bug

#227 640 Provide Vector( std::initializer_list<T> ) constructor
  include/graphblas/base/vector.hpp
  include/graphblas/bsp1d/vector.hpp
  include/graphblas/hyperdags/io.hpp
  include/graphblas/hyperdags/vector.hpp
  include/graphblas/nonblocking/coordinates.hpp
  include/graphblas/nonblocking/vector.hpp
  include/graphblas/reference/vector.hpp
  tests/unit/CMakeLists.txt
  tests/unit/eWiseLambda.cpp
  tests/unit/unittests.sh
  tests/unit/vectorFromListConstructor.cpp
Labels: enhancement

#292 259 nonblocking backend uses a dynamic schedule
  include/graphblas/base/blas3.hpp
  include/graphblas/nonblocking/coordinates.hpp
  src/graphblas/nonblocking/pipeline.cpp
Labels: bug

#307 Fix typo in perftests
  tests/performance/performancetests.sh
  tests/summarise.sh
Labels: bug, cleanup

#299 Issue #293: fixing generation of installation infrastructure
  include/CMakeLists.txt
Labels: bug

#298 Wrong values printed in debug output
  tests/utils/matrix_values_check.hpp
Labels: bug

#309 Add preconditioning to the ALP CG solvers
  include/graphblas.hpp
  include/graphblas/algorithms/conjugate_gradient.hpp
  include/graphblas/base/alloc.hpp
  include/graphblas/base/distribution.hpp
  include/graphblas/bsp1d/blas1.hpp
  include/graphblas/bsp1d/blas2.hpp
  include/graphblas/bsp1d/distribution.hpp
  include/graphblas/bsp1d/io.hpp
  include/graphblas/bsp1d/matrix.hpp
  include/graphblas/bsp1d/vector.hpp
  include/graphblas/hyperdags/io.hpp
  include/graphblas/nonblocking/blas2.hpp
  include/graphblas/nonblocking/forward.hpp
  include/graphblas/nonblocking/matrix.hpp
  include/graphblas/nonblocking/vector.hpp
  include/graphblas/reference/blas1.hpp
  include/graphblas/reference/blas2.hpp
  include/graphblas/reference/forward.hpp
  include/graphblas/reference/matrix.hpp
  include/graphblas/utils/iscomplex.hpp
  include/transition/blas_sparse.h
  include/transition/blas_sparse_vec.h
  include/transition/kml_iss.h
  include/transition/solver.h
  include/transition/spblas.h.in
  include/transition/spblas_impl.h
  src/transition/CMakeLists.txt
  src/transition/kml_iss.cpp
  src/transition/solver.cpp
  tests/smoke/conjugate_gradient.cpp
  tests/smoke/smoketests.sh
Labels: bug, enhancement

#315 More testing found a bug in kml_iss implementation, herewith fixed
  src/transition/kml_iss.cpp
Labels: bug

#288 Issue #261: adding missing dense descriptor and delete unnecessary se…
  include/graphblas/algorithms/simple_pagerank.hpp
  include/graphblas/banshee/blas1.hpp
  include/graphblas/base/blas1.hpp
  include/graphblas/base/blas2.hpp
  include/graphblas/bsp1d/blas1.hpp
  include/graphblas/bsp1d/blas2.hpp
  include/graphblas/bsp1d/matrix.hpp
  include/graphblas/bsp1d/vector.hpp
  include/graphblas/hyperdags/blas1.hpp
  include/graphblas/hyperdags/blas2.hpp
  include/graphblas/hyperdags/blas3.hpp
  include/graphblas/nonblocking/blas1.hpp
  include/graphblas/nonblocking/blas2.hpp
  include/graphblas/reference/blas1.hpp
  include/graphblas/reference/blas2.hpp
  include/graphblas/reference/forward.hpp
  include/graphblas/reference/matrix.hpp
  tests/banshee/simple_pagerank.cpp
  tests/smoke/hook/small_simple_pagerank.cpp
  tests/smoke/simple_pagerank.cpp
  tests/smoke/simple_pagerank_broadcast.cpp
  tests/smoke/simple_pagerank_from_mpi.cpp
Labels: bug, documentation

#188 633 Provide grb::foldl/foldr( [in,out] T&, [in] Matrix<D>, monoid )
  include/graphblas/base/blas3.hpp
  include/graphblas/blas0.hpp
  include/graphblas/bsp/utils.hpp
  include/graphblas/bsp1d/blas3.hpp
  include/graphblas/bsp1d/matrix.hpp
  include/graphblas/hyperdags/blas3.hpp
  include/graphblas/hyperdags/hyperdags.hpp
  include/graphblas/nonblocking/blas3.hpp
  include/graphblas/reference/blas3.hpp
  include/graphblas/reference/compressed_storage.hpp
  include/graphblas/utils.hpp
  src/graphblas/CMakeLists.txt
  src/graphblas/bsp/utils.cpp
  src/graphblas/hyperdags/hyperdags.cpp
  tests/unit/CMakeLists.txt
  tests/unit/fold_matrix_to_scalar.cpp
  tests/unit/unittests.sh
Labels: enhancement

#300 665 set up continuous benchmarking
  .gitignore
  .gitlab-ci.yml
Labels: enhancement
